---
- name: "Ensure PostgreSQL extensions are present for {{ postgresql_extension_group.name }}."
  community.postgresql.postgresql_ext:
    name: "{{ extension_name }}"
    db: "{{ postgresql_extension_group.name }}"
    schema: "{{ postgresql_extension_group.schema | default(omit) }}"
    login_host: "{{ postgresql_extension_group.login_host | default('localhost') }}"
    login_password: "{{ postgresql_extension_group.login_password | default(omit) }}"
    login_user: "{{ postgresql_extension_group.login_user | default(postgresql_user) }}"
    login_unix_socket: "{{ postgresql_extension_group.login_unix_socket | default(postgresql_unix_socket_directories[0]) }}"
    port: "{{ postgresql_extension_group.port | default(omit) }}"
    state: "{{ postgresql_extension_group.state | default('present') }}"
  loop: "{{ postgresql_extension_group.extensions | default([]) | unique }}"
  loop_control:
    loop_var: extension_name
  become: true
  become_user: "{{ postgresql_user }}"
