---

- name: Populate variables
  ansible.builtin.import_tasks: variables.yml

- name: Install postgresql
  ansible.builtin.import_tasks: setup.yml

- name: Initialize system
  ansible.builtin.import_tasks: initialize.yml

- name: Configure postgresql
  ansible.builtin.import_tasks: configure.yml

- name: Ensure PostgreSQL is started and enabled on boot.
  ansible.builtin.service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_service_state }}"
    enabled: "{{ postgresql_service_enabled }}"

- name: Configure users
  ansible.builtin.import_tasks: users.yml

- name: Configure databases
  ansible.builtin.import_tasks: databases.yml

- name: Configure user properties
  ansible.builtin.import_tasks: users_props.yml
