---
- name: Ensure PostgreSQL Python libraries are installed.
  ansible.builtin.apt:
    name: "{{ __postgresql_python_library }}"
    state: present

- name: Add postgresql signing key
  ansible.builtin.get_url:
    url: "{{ __postgresql_signing_key }}"
    dest: /etc/apt/trusted.gpg.d/postgresql.asc
    mode: '0644'
    force: true

- name: Add postgresql repository
  ansible.builtin.apt_repository:
    repo: "{{ __postgresql_repository }}"
    update_cache: true

- name: Ensure PostgreSQL packages are installed.
  ansible.builtin.apt:
    name: "{{ postgresql_packages }}"
    state: present

- name: Ensure all configured locales are present.
  community.general.locale_gen:
    name: "{{ item }}"
    state: present
  loop: "{{ postgresql_locales }}"
  register: locale_gen_result

- name: Force-restart PostgreSQL after new locales are generated.
  ansible.builtin.service:
    name: "{{ postgresql_daemon }}"
    state: restarted
  when: locale_gen_result.changed
