---
- name: Converge
  hosts: all
  become: true

  tasks:
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Check that postgresql service is running
      ansible.builtin.assert:
        that:
          - ansible_facts.services['postgresql@' + postgresql_version | string + '-main.service'].state == 'running'
          - ansible_facts.services['postgresql@' + postgresql_version | string + '-main.service'].status == 'active'

    - name: Verify pgpass
      ansible.builtin.file:
        path: /var/lib/postgresql/.pgpass
        state: file
        owner: postgres
        group: postgres
        mode: 0600
      register: __pgpass_file
      check_mode: true

    - name: Checks on pgpass
      ansible.builtin.assert:
        that:
          - __pgpass_file.changed is false

    - name: Check extensions exist
      community.postgresql.postgresql_query:
        db: example
        query: "SELECT extname FROM pg_extension WHERE extname IN ('hstore', 'citext');"
      become: true
      become_user: postgres
      register: __extensions_query

    - name: Assert extensions are present
      ansible.builtin.assert:
        that:
          - (__extensions_query.query_result | map(attribute='extname') | list | sort) == ['citext', 'hstore']
