---

# ----------------------------
# Role: postgresql
# ----------------------------

postgresql_version: 15
postgresql_databases:
  - name: example
postgresql_users:
  - name: jdoe
    password: mypassword

postgresql_pgpass_users:
  - name: jdoe
    database: example
  - hostname: localhost
    port: 5432
    database: '*'
    name: postgres
    password: ''
